module.exports = {
    code: 200,
    data: [
        {
            path: "/home/index",
            name: "home",
            component: "/home/index",
            meta: {
                icon: "HomeFilled",
                title: "首页",
                isLink: "",
                isHide: false,
                isFull: false,
                isAffix: true,
                isKeepAlive: true,
            },
        },
        {
            path: "/class_management",
            name: "class_management",
            redirect: "/class_management/schedule_management",
            meta: {
                icon: "Histogram",
                title: "班级管理",
                isLink: "",
                isHide: false,
                isFull: false,
                isAffix: false,
                isKeepAlive: true,
            },
            children: [
                {
                    path: "/class_management/classList_info",
                    name: "classList_info",
                    component: "/class_management/classList_info/index",
                    meta: {
                        icon: "Histogram",
                        title: "班级列表",
                        isLink: "",
                        isHide: false,
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
                {
                    path: "/class_management/student_management/:name",
                    name: "student_management",
                    component: "/class_management/student_management/index",
                    meta: {
                        icon: "Histogram",
                        title: "班级详情",
                        isLink: "",
                        isHide: false,
                        // activeMenu: "/class_management/student_management",
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
                {
                    path: "/class_management/schedule_management",
                    name: "schedule_management",
                    component: "/class_management/schedule_management/index",
                    meta: {
                        icon: "Histogram",
                        title: "课表管理",
                        isLink: "",
                        isHide: false,
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
                {
                    path: "/class_management/auditionlist_management",
                    name: "auditionlist_management",
                    component: "/class_management/auditionlist_management/index",
                    meta: {
                        icon: "Histogram",
                        title: "试听课管理",
                        isLink: "",
                        isHide: false,
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
            ],
        },
        {
            path: "/classroom_management",
            name: "classroom_management",
            redirect: "/classroom_management/classroom_list",
            meta: {
                icon: "Histogram",
                title: "教室管理",
                isLink: "",
                isHide: false,
                isFull: false,
                isAffix: false,
                isKeepAlive: true,
            },
            children: [
                {
                    path: "/classroom_management/classroom_list",
                    name: "classroom_list",
                    component: "/classroom_management/classroom_list/index",
                    meta: {
                        icon: "Histogram",
                        title: "教室列表",
                        isLink: "",
                        isHide: false,
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
                {
                    path: "/classroom_management/classroom_time",
                    name: "classroom_time",
                    component: "/classroom_management/classroom_time/index",
                    meta: {
                        icon: "Histogram",
                        title: "教室安排时间查询",
                        isLink: "",
                        isHide: false,
                        isFull: false,
                        isAffix: false,
                        isKeepAlive: true,
                    },
                },
            ],
        },
        {
            path: "/teacher_management",
            name: "teacher_management",
            component: "/teacher_management/index",
            meta: {
                icon: "Histogram",
                title: "教师管理",
                isLink: "",
                isHide: false,
                isFull: false,
                isAffix: false,
                isKeepAlive: true,
            },
        },
    ],
    msg: "成功",
};
